MESSAGE(STATUS "Loading ${VTK_DIR}/CMakeCache.txt")

LOAD_CACHE(${VTK_DIR} READ_WITH_PREFIX VTK42_
  VTK_USE_SYSTEM_ZLIB
  VTK_USE_SYSTEM_PNG
  VTK_USE_SYSTEM_TIFF
  VTK_USE_SYSTEM_EXPAT
)

MESSAGE(STATUS "VTK Use System ZLIB  ${VTK42_VTK_USE_SYSTEM_ZLIB}")
MESSAGE(STATUS "VTK Use System PNG   ${VTK42_VTK_USE_SYSTEM_PNG}")
MESSAGE(STATUS "VTK Use System TIFF  ${VTK42_VTK_USE_SYSTEM_TIFF}")
MESSAGE(STATUS "VTK Use System EXPAT ${VTK42_VTK_USE_SYSTEM_EXPAT}")

# VTK_ZLIB_LIBRARIES
IF (${VTK42_VTK_USE_SYSTEM_ZLIB})
  # Use system library
  FIND_PACKAGE(ZLIB)
  IF(ZLIB_FOUND)
    SET(VTK_ZLIB_LIBRARIES ${ZLIB_LIBRARIES})
  ENDIF(ZLIB_FOUND)
ELSE (${VTK42_VTK_USE_SYSTEM_ZLIB})
  # Use VTK library
  SET(VTK_ZLIB_LIBRARIES vtkzlib)
ENDIF (${VTK42_VTK_USE_SYSTEM_ZLIB})
MESSAGE(STATUS "Loaded ZLIB ${VTK_ZLIB_LIBRARIES}")

# VTK_PNG_LIBRARIES
IF (${VTK42_VTK_USE_SYSTEM_PNG})
  # Use system library
  FIND_PACKAGE(PNG)
  IF(PNG_FOUND)
    SET(VTK_PNG_LIBRARIES ${PNG_LIBRARIES})
  ENDIF(PNG_FOUND)
ELSE (${VTK42_VTK_USE_SYSTEM_PNG})
  # Use VTK library
  SET(VTK_PNG_LIBRARIES vtkpng)
ENDIF (${VTK42_VTK_USE_SYSTEM_PNG})
MESSAGE(STATUS "Loaded PNG ${VTK_PNG_LIBRARIES}")

# VTK_TIFF_LIBRARIES
IF (${VTK42_VTK_USE_SYSTEM_TIFF})
  # Use system library
  FIND_PACKAGE(TIFF)
  IF(TIFF_FOUND)
    SET(VTK_TIFF_LIBRARIES ${TIFF_LIBRARIES})
  ENDIF(TIFF_FOUND)
ELSE (${VTK42_VTK_USE_SYSTEM_TIFF})
  # Use VTK library
  SET(VTK_TIFF_LIBRARIES vtktiff)
ENDIF (${VTK42_VTK_USE_SYSTEM_TIFF})
MESSAGE(STATUS "Loaded TIFF ${VTK_TIFF_LIBRARIES}")

# VTK_EXPAT_LIBRARIES
IF (${VTK42_VTK_USE_SYSTEM_EXPAT})
  # Use system library
  # This does not exists:
  #FIND_PACKAGE(EXPAT)
  #IF(EXPAT_FOUND)
  #  SET(VTK_EXPAT_LIBRARIES ${EXPAT_LIBRARIES})
  #ENDIF(EXPAT_FOUND)
  MESSAGE( FATAL_ERROR "Support for VTKDCMTK_WITH_EXPAT requires that VTK was compiled with Utilities/expat")
ELSE (${VTK42_VTK_USE_SYSTEM_EXPAT})
  # Use VTK library
  SET(VTK_EXPAT_LIBRARIES vtkexpat)
ENDIF (${VTK42_VTK_USE_SYSTEM_EXPAT})
MESSAGE(STATUS "Loaded EXPAT ${VTK_EXPAT_LIBRARIES}")